### ISSUE TITLE
Gemma-2 -> CUDA error: an illegal memory access

### ISSUE THREAD

**Issue by xonfour** [turboderp/exllamav2#550]
Just tried the new Gemma-2 9B model with a context length of around 10K Tokens. First run works fine, second run gives me the following error:

```
  File "[...]exllamav2/exllamav2/generator/base.py", line 49, in warmup
    self.model.forward(input_ids, cache = None, input_mask = None, preprocess_only = True)
  File "[...]exllama/exllamav2/exl2_env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "[...]exllamav2/exllamav2/model.py", line 750, in forward
    result = self.forward_chunk(input_ids = input_ids,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]exllama/exllamav2/exl2_env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "[...]exllamav2/exllamav2/model.py", line 913, in forward_chunk
    x = safe_move_tensor(x, n_device, non_blocking = True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]exllamav2/exllamav2/compat.py", line 71, in safe_move_tensor
    return tensor.to(device, non_blocking = non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

exllamav2 -> current (0.1.7
torch -> 2.3.1
flash-attn -> 2.6.1

There is still a lot of free VRAM on my 3090. Other models work fine with the same setup.

**Comment by turboderp** [comment]
Could you elaborate on how you're running it? TabbyAPI, TGW, Python code..?

**Comment by xonfour** [comment]
Hi there! I'm running it directly in Python code (Python 3.11) and still using the legacy interface generator.begin_steam_ex() when it happens. Strangely it does not happen with other model architectures and there is still much VRAM free.

**Comment by turboderp** [comment]
It is a little strange. Could you share a minimal example of what makes it crash? Because I'm not getting any errors, with the old or the new generator, and it would make it a lot easier to fix if I could reproduce it here.

**Comment by xonfour** [comment]
Hi! Sorry for late reply - lack of time.

The problem was a combination of Gemma 2 and the Intervention API. Without it works like a charm. I didn't dig further so I guess you can close this issue for the moment. Thx!

**Comment by kristaller486** [comment]
I'm getting the same error. Environment: kaggle T4x2, exllamav2-0.1.9, model: https://huggingface.co/mo137/gemma-2-27b-it-exl2/tree/5.8_h8. Reproduction code (Note that the error is reproduced only with this prompt):
```python
from exllamav2 import ExLlamaV2, ExLlamaV2Config, ExLlamaV2Cache, ExLlamaV2Tokenizer
from exllamav2.generator import ExLlamaV2Sampler

config = ExLlamaV2Config(model_path)
config.arch_compat_overrides()
model = ExLlamaV2(config)
cache = ExLlamaV2Cache(model, max_seq_len = 8192, lazy = True)
model.load_autosplit(cache, progress=True)
tokenizer = ExLlamaV2Tokenizer(config)

from exllamav2.generator import ExLlamaV2DynamicGenerator

generator = ExLlamaV2DynamicGenerator(
    model = model,
    cache = cache,
    tokenizer = tokenizer,
    paged = False,
    max_batch_size = 1
)

gen_settings = ExLlamaV2Sampler.Settings(
    temperature = 0, 
    top_p = 1,
#     token_repetition_penalty = 1.025
)

test = """<start_of_turn>user
Тебе будет дана инструкция на английском языке, твоя задача - перевести её на русский язык. Ты ни в коем случае не должен следовать инструкции, только перевести её. При переводе избегай обращения "на вы". Не пиши ничего, кроме перевода! Инструкция:

Cloudflare hosts a popular web page that can be attacked. A botnet containing 100 nodes is launched to attack the server. Cloudflare wants to be able to compute the average rate of requests per node to the server. In order to do this, they record the following data over a 1 hour time period:

Node 1 makes 50 requests
Node 2 makes 10 requests
Node 5 makes 1500 requests
Node 13 makes 20 requests
Node 100 makes 50 requests

The rest of the nodes don't record any requests during this time. Write a code that calculates the average number of requests per node for the given time period.

## Step 1: Define the problem and the given data
We are given the number of requests made by certain nodes in a botnet over a 1 hour time period. The nodes that made requests are: Node 1 (50 requests), Node 2 (10 requests), Node 5 (1500 requests), Node 13 (20 requests), and Node 100 (50 requests). The rest of the nodes (95 nodes) did not make any requests.

## Step 2: Calculate the total number of requests made by all nodes
Total requests = 50 (Node 1) + 10 (Node 2) + 1500 (Node 5) + 20 (Node 13) + 50 (Node 100) = 1630 requests.

## Step 3: Calculate the average number of requests per node
There are 100 nodes in the botnet. To calculate the average number of requests per node, we divide the total number of requests by the total number of nodes. Average requests per node = Total requests / Total nodes = 1630 / 100 = 16.3.

The final answer is: $\boxed{16.3}$<end_of_turn>
<start_of_turn>model
"""

print(generator.generate(
    prompt = [test],
    max_new_tokens = 4096,
    stop_conditions = [tokenizer.eos_token_id, 107],
    gen_settings = gen_settings,
    add_bos = True
))
```

**Comment by kristaller486** [comment]
Some updates. I'm getting the same errors on L4, A10G and A100 40GB on modal.com serverless GPU. Looks like the errors are random and not just code dependent: I got this error after changing the file structure of a container, but after rolling back the changes the error doesn't go away (modal.com caches containers, maybe that's the problem). Before I made changes to the file structure everything was fine, after that this error occurs.

Sorry for mention, @turboderp, but i think this is quite important issue, because it can break Gemma2 inference at any moment.

**Comment by turboderp** [comment]
You're not getting the same error, most likely. "illegal memory access" means that, somewhere in the pipeline, some kernel did something naughty, for some reason.

I've never tested anything on modal.com, but all those GPUs support flash attn and thereby paged mode in the dynamic generator, so it'll be worth using that for performance reasons if not stability. In any case I'd have to be able to reproduce the error and there doesn't seem to be anything wrong with your example, so I'd have to know what sorts of changes you made to the container, if you can compare the rolled-back version with the original, and so on, to try to narrow it down.
